version: '3.8'

services:
  web:
    build: .
    ports:
      - "3100:3100"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=postgresql://quicklink_owner:npg_gWb5U1GDrETv@ep-cold-lake-a4xlf6bc-pooler.us-east-1.aws.neon.tech/quicklink?sslmode=require
    restart: always

volumes:
  postgres_data: 