version: '3.8'

services:
  web:
    build: .
    ports:
      - "3100:3100"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=urlshortener
      - POSTGRES_PASSWORD=urlshortener
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  url-shortener-net:
    driver: bridge 