version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://urlshortener:urlshortener@db:5432/urlshortener
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - url-shortener-net
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0 --port=3000"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=urlshortener
      - POSTGRES_PASSWORD=urlshortener
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  url-shortener-net:
    driver: bridge 