version: '3.8'

services:
  web:
    build: .
    ports:
      - "3100:3100"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL} # Env resetted
    restart: always

volumes:
  postgres_data: 
