"""Add Firebase authentication fields

Revision ID: 76e64c2cf372
Revises: d8df9ef6e802
Create Date: 2025-05-04 14:42:14.615749

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '76e64c2cf372'
down_revision = 'd8df9ef6e802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=512), nullable=True))
        batch_op.create_unique_constraint('uq_user_firebase_uid', ['firebase_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_firebase_uid', type_='unique')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
